### ISSUE TITLE
No longer builds Arch

### ISSUE THREAD

**Issue by jayray-git** [aabc/ipt-netflow#227]
ipt-netflow/ipt_NETFLOW.c:4090:17: error: implicit declaration of function ‘strlcpy’; did you mean ‘strscpy’? [-Werror=implicit-function-declaration]
 4090 |                 strlcpy(info.driver, dev->dev.parent->driver->name, sizeof(info.driver));
      |                 ^~~~~~~
      |                 strscpy
cc1: some warnings being treated as errors
make[3]: *** [scripts/Makefile.build:243: ipt-netflow/ipt_NETFLOW.o] Error 1
make[2]: *** [/usr/lib/modules/6.8.2-arch2-1/build/Makefile:1921: ipt-netflow] Error 2
make[1]: *** [Makefile:240: __sub-make] Error 2
make[1]: Leaving directory '/usr/lib/modules/6.8.2-arch2-1/build'
make: *** [Makefile:27: ipt_NETFLOW.ko] Error 2

**Comment by svlobanov** [comment]
strlcpy has been removed from Linux kernel: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=d26270061ae66b915138af7cd73ca6f8b85e6b44

try to replace strlcpy to strscpy

**Comment by jayray-git** [comment]
perl -pi -e 's/strlcpy/strscpy/' *
^works

**Comment by svlobanov** [comment]
Please re-open the issue. It should be fixed in master branch. Otherwise, somebody else will open the same issue

**Comment by jayray-git** [comment]
*reopened

**Comment by juju4** [comment]
Still seeing strlcopy here and few more
https://github.com/aabc/ipt-netflow/blob/master/ipt_NETFLOW.c#L4090
wrongly fixed by adding back strlcopy in https://github.com/aabc/ipt-netflow/pull/230

Confirming suggested replacement works directly as per https://github.com/juju4/ansible-ipt-netflow/actions/runs/11655352850/job/32449937461

**Comment by jayray-git** [comment]
https://github.com/aabc/ipt-netflow/issues/235 @juju4 there are mote issues - patch fixes.
